<?php
/**
 * One-time key generation for V2 PII encryption.
 * Run: php scripts/generate_encryption_keys.php
 *
 * Writes secrets to .env (gitignored). Never commit .env or PEM files.
 */
declare(strict_types=1);

$projectRoot = dirname(__DIR__);
$envPath = $projectRoot . '/.env';
$examplePath = $projectRoot . '/.env.example';

if (php_sapi_name() !== 'cli') {
    fwrite(STDERR, "Run this script from the command line only.\n");
    exit(1);
}

// --- RSA key pair ---
$config = [
    'private_key_bits' => 2048,
    'private_key_type' => OPENSSL_KEYTYPE_RSA,
];
$res = openssl_pkey_new($config);
if ($res === false) {
    fwrite(STDERR, "Failed to generate RSA key pair.\n");
    exit(1);
}

openssl_pkey_export($res, $privatePem);
$details = openssl_pkey_get_details($res);
$publicPem = $details['key'] ?? '';
if ($publicPem === '') {
    fwrite(STDERR, "Failed to export public key.\n");
    exit(1);
}

// --- AES-256 data key ---
$aesKey = random_bytes(32);

$encryptedAes = '';
$ok = openssl_public_encrypt($aesKey, $encryptedAes, $publicPem, OPENSSL_PKCS1_OAEP_PADDING);
if (!$ok) {
    fwrite(STDERR, "Failed to wrap AES key with RSA public key.\n");
    exit(1);
}

$encryptedAesB64 = base64_encode($encryptedAes);

$escape = static function (string $pem): string {
    return str_replace(["\r\n", "\r", "\n"], '\\n', trim($pem));
};

$envContent = <<<ENV
# Generated by scripts/generate_encryption_keys.php — DO NOT COMMIT
ENCRYPTION_ENABLED=true

RSA_PRIVATE_KEY="{$escape($privatePem)}"
RSA_PUBLIC_KEY="{$escape($publicPem)}"
ENCRYPTED_AES_KEY={$encryptedAesB64}

# Database (adjust for your XAMPP setup)
DB_HOST=127.0.0.1
DB_NAME=PTUD_Final
DB_USER=root
DB_PASS=
ENV;

if (is_file($envPath)) {
    echo "WARNING: {$envPath} already exists. Writing to .env.generated instead.\n";
    $envPath = $projectRoot . '/.env.generated';
}

file_put_contents($envPath, $envContent);
chmod($envPath, 0600);

echo "Keys generated successfully.\n";
echo "  Written: {$envPath} (mode 0600)\n";
echo "\nNext steps:\n";
echo "  1. If file is .env.generated, rename/copy to .env\n";
echo "  2. Run: mysql ... < database/migrations/001_v2_encryption_schema.sql\n";
echo "  3. Run: php scripts/migrate_encrypt_existing_data.php\n";
echo "  4. Set ENCRYPTION_ENABLED=true in .env\n";
